baseurl = "http://abelino.github.io/blog"
title = "abeli.no"
theme = "simple-a"
languageCode = "en-us"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
[indexes]
   category = "categories"
   tag = "tags"
